changelog:
  categories:
    - title: ğŸ• aaa Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: ğŸ‘’ Dependencies
      labels:
        - dependencies